baseurl = "https://alexsavin.me/"
title = "Alex Savin"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 50
canonifyurls = true

pygmentsstyle = "borland"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[markup.goldmark.renderer]
    unsafe= true

[params]
    author = "Alex Savin"
    info = "Software Engineer and Filmmaker"
    description = "Alex Savin's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Email me at hello@alexsavin.me"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Hide the toggle button, along with the associated vertical divider
    hidecolorschemetoggle = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/asavin/"
[[params.social]]
    name = "Mastodon"
    icon = "fa fa-mastodon fa-2x"
    weight = 2
    url = "https://mastodon.social/@alexsavin"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 6
    url = "https://alexsavin.me/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Hire me"
    weight = 3
    url = "/hire/"
